# Logging (global defaults)
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Enabled modules
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SPI=y

# Shells
CONFIG_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_SPI_SHELL=y

# Sensor support
CONFIG_SENSOR=y
CONFIG_BME280=y

# LCD-Anzeige (HD44780 ueber PCF8574T I2C-GPIO-Expander)
CONFIG_AUXDISPLAY=y
CONFIG_GPIO_PCF857X=y
